### ISSUE TITLE
Classes gone when restarting UE Editor

### ISSUE THREAD

**Issue by bogdankatishev** [sinbad/StevesUEHelpers#9]
Hello,

When making the widgets, I can choose the "Focusable" user widget class. When I save everything and restart my Editor/Computer, the parent classes of the widgets are getting lost:
![widget_lost](https://github.com/sinbad/StevesUEHelpers/assets/41480199/a18853d2-15aa-40ed-970e-6f07890f0866)
![widget_lost2](https://github.com/sinbad/StevesUEHelpers/assets/41480199/739d1a2b-e18f-47b5-ac54-14ac813056e5)

I followed the installation and included everything in Build.cs file (I am also using your other helpers like SPUD etc... and they all work).

I already deleted all cache folders (Binaries, DerivedDataCache, Intermediate etc...) and fully rebuild the project in VS code etc...

Any ideas?

(I'm using UE5.1, the SUDS example project also works with this version)

**Comment by sinbad** [comment]
I've started to occasionally get this recently in one of my example projects and I haven't been able to figure out why, except that simply restarting the editor usually fixes it. I've recently added a plugin entry for StevesUEHelpers to my project to see if that makes a difference - I've seen the problem once since then but it seems to be less often? I've never had this problem until 5.1 so I think it might be an editor bug, it's just hard to reproduce since it goes away on its own.

**Comment by sinbad** [comment]
I'm starting to wonder if it's a timing problem, perhaps changing the LoadingPhase might help

**Comment by bogdankatishev** [comment]
Hello,

I can confirm that adding StevesUEHelpers to .uproject modules list and changing the LoadingPhase to "PreDefault" works like a charm.

```
{
	"Name": "StevesUEHelpers",
	"Type": "Runtime",
	"LoadingPhase": "PreDefault"
}
```

**Comment by sinbad** [comment]
Thanks, I've changed the LoadingPhase, hopefully this goes away for good this time!
